### ISSUE TITLE
large file and streaming support

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#106]
Autograph should support signing files that don't fit in memory (e.g. xpi, apk, and mar files).

This could look like:

- [ ] change the API to support chunked http requests (or maybe http/2 eventually) 
  * the first chunk consists of the usual JSON request body except with "input_hash", "input_hash_type", "input_size" fields replacing "input"
    * "input_hash_type" (string) is the type hash function to use (TBD these should probably be from some set of IANA values) and cannot be null/empty/undefined/"none" or md5.
    * "input_hash" (string) is the result of apply hash of `input_hash_type` to the file bytes (not base64 encoded)
    * "input_size" (uint) is the size of the file in bytes up to some application or signer configurable max size

```json
[
    {
         "input_hash":"b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c",
         "input_hash_type":"sha256",
         "input_size": "9001"
    },
    ... other signing requests
]
```

if none of the JSON signing requests contain hash inputs, signing proceeds as normal.

  * the subsequent chunks have content type application/octet-string and must occur in the order specified in the JSON signing requests, have a matching input_hash and input_size
  * the hawk header payload only hashes the first chunk of JSON body

- [ ] change the request handlers to check for available disk space and 
reject with a 429 and retry-after or stream to a [temp file](https://golang.org/pkg/io/ioutil/#TempFile) 
  * start a signer goroutine to sign the tempfile in-place or fail (per the end-to-end principle let the clients retry)
  * upon completion stream the result back

  Alternatively, this could be a signer worker pool or separate processes (though go does M:N so not sure how that'd work)

+'s:

* backwards compatibility
* larger file support
* could split signers from server (e.g. so we don't need to run the webserver to sign from CLI like the signtool/signingerserver split in releng)

-'s:

* clients need to know file hashes upfront
* clients must keep a copy of the files to retry
* still sending whole files over the network

**Comment by jvehent** [comment]
That could work in principle, though I'd suggest not caring about backward compatibility and creating a new `/sign/octet-stream` endpoint for this.

To sign a MAR file, you'd need to start calculating the hash of the signable block right away, which means changing go.mozilla.org/mar as well.

I don't think this would work for XPI/APK because we need the full zip before we can calculate the manifest, which means loading it into memory.

**Comment by g-k** [comment]
Not sure how we'd do payload validation for a `/sign/octet-stream`.
 
Closing since we'll probably need testing and the quickfix would be to scale up and have requests check for available memory and return 429 if they don't have enough memory.
