### ISSUE TITLE
switch to go modules

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#115]
~~https://github.com/golang/dep~~ https://github.com/golang/go/wiki/vgo

Benefits:

* don't need to vendor all deps
* can write lockfile of recent

Downsides:

* need to trust the tool
* tool is relatively new
* requires newer versions of git and access to internet in builds
* downloading deps can incur CI failures when they fail and make CI flakey

**Comment by g-k** [comment]
thoughts @ajvb @milescrabill @jvehent ?

**Comment by ajvb** [comment]
I'd switch to vgo as it will become the new standard (https://github.com/golang/go/wiki/vgo)

moz examples:
https://github.com/mozilla-services/autograph-edge/blob/master/Makefile#L12
https://github.com/mozilla-services/cloudtrail-streamer/blob/master/Makefile#L35

**Comment by ajvb** [comment]
In that wiki page, it does state `For any production workloads, use dep, or migrate to it if you have not done so already.` + `The [vgo] proposal has been accepted and will be merged in the Go tree and replace dep at a later date.`

But I've been using vgo on two projects with great success + ease.

**Comment by g-k** [comment]
oh right, that's better!  I want say the one I was thinking of @ajvb. E_TOO_MANY_TOOLS

**Comment by ajvb** [comment]
>need to trust the tool

I trust `vgo`, and it is now under the same development management / code review process as `go` and all standard tooling, but yeah it is very new.

>tool is relatively new

I've seen some bugs appear and be fixed since I have started using it, but so far they have all resulted in the initial build blowing up, so it's very obvious.

>requires newer versions of git and access to internet in builds
>downloading deps can incur CI failures when they fail and make CI flakey

Yeah absolutely. Is there anything in autograph's release/test pipeline that may make this a bigger problem than it would be on another project?

**Comment by g-k** [comment]
> Is there anything in autograph's release/test pipeline that may make this a bigger problem than it would be on another project?

I have run into vgo needing a newer version of git (>= 2.18 or something), but that's it.

**Comment by ajvb** [comment]
>I have run into vgo needing a newer version of git (>= 2.18 or something), but that's it.

Oh yeah, I do believe that is the case.

**Comment by g-k** [comment]
Not sure how far out it is, but maybe waiting for vgo to land / go 1.11 is best.

**Comment by g-k** [comment]
OK let's do this just not right away.

**Comment by g-k** [comment]
fixed in https://github.com/mozilla-services/autograph/pull/330
