### ISSUE TITLE
figure out downstream/dependent docker image testing

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#129]
Nice to have. It'd be good to test new autograph versions against dependent services in CI (to catch things like incorrectly adding the port option earlier breaking addons).

Dependent services:

* addons-server: https://github.com/mozilla/addons-server/blob/cd3c45fcda542e5fb5a79c07750e721ecb0b9139/.travis.yml#L68
* signingscript: https://github.com/mozilla-releng/signingscript/blob/ff38d44952b1088607ffd9d806f3161c689df568/.travis.yml#L20
* normandy: https://github.com/mozilla/normandy/blob/c654465c615b7939787759a107f8ae9253cd971e/compose/normandy-base.yml#L32
* kinto?

Also, XPI and APK signing from CI (primarily via edge): 

* for screenshots: https://github.com/mozilla-services/screenshots/blob/3286c1910077ac6528d7a861a925b934256850e3/Makefile#L120
* APKs ...

I see a few options here:

* switch all dependents to latest and don't break autograph
* publish a stable tag and switch dependents to it
* manually update dependents to a pinned version with each release
* have downstream services run against both, but only fail on stable / the latest tag (like how rust-lang's crater services tests Nightly rust versions against all open source libs)

**Comment by g-k** [comment]
This is also a general problem for testing with testing downstream/dependent services.

**Comment by peterbe** [comment]
For normandy, I'm pretty sure we entirely mock the autograph call in CI. 

For kinto, it's [kinto-dist](https://github.com/mozilla-services/kinto-dist) and the autograph is used in smoke tests based on [this `Dockerfile` here](https://github.com/mozilla-services/kinto-dist/blob/master/autograph/Dockerfile#L1).

**Comment by g-k** [comment]
I think we'll just have downstream projects use dependabot for Dockerfiles to stay up to date for now.
