### ISSUE TITLE
OSX code signing

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#143]
Per prior discussion with @jvehent, move [Fx OSX signing](https://developer.mozilla.org/en-US/docs/Mozilla/Signing_Mozilla_apps_for_Mac_OS_X) to autograph.

This frees up Rel{Eng,Ops} from having to run OSX machines in the datacenter for signing and simplifies 
routes too.

Some pieces already exist:

* @jvehent has a WIP PR to handle the PKCS7 timestamp part: https://github.com/mozilla-services/pkcs7/pull/14

* :ted / @luser has a rust library for parsing the application bundle (TODO: find out where this lives)

Implementation-wise we have a few options to integrate this with autograph:

* link the rust parser into signingscript and use autograph `/sign/hash` or `/sign/data`
* link the rust parser w/ cgo FFI and use autograph `/sign/file`
* implement a parser in go and use autograph `/sign/file`

**Comment by luser** [comment]
My Rust crate is here: https://github.com/luser/darwincodesign

It's not entirely complete. IIRC it can parse the code signature out of an existing Mach-O binary and verify the code hashes, but there are also other hashes in there ([the special hash slots listed here](https://opensource.apple.com/source/Security/Security-55471.14.18/libsecurity_codesigning/lib/codedirectory.h.auto.html), starting with `cdInfoSlot`) for things like Info.plist that aren't currently calculated by that code. I don't think implementing those would be incredibly hard.

I haven't looked at this code in a little while so I'm fuzzy on all the details, but the signature is stored in the linkedit segment of the binary and located with the `LC_CODE_SIGNATURE` load command. The signature is a complicated binary format ("Blobs" and "SuperBlobs" and such) but it boils down to having a few embedded bits:
* A "code directory" that has hashes of each page of the binary (up to but not including the signature at the end of the binary) as well as hashes of the "special slots" like the Info.plist and requirements.
* The app requirements
* The PKCS#7 signature, which signs just a hash of the code directory

If you clone that repo you can `cargo run print /path/to/binary` to dump the signature data that the tool knows about. Doing that for Firefox 58.0.2 (the latest Firefox release verison I have on my Mac) outputs:
```
EmbeddedSignature {
    0: CodeDirectory(
        CodeDirectory {
            cdhash: SHA-1:769753c01c9a67d67e3152484e47e15527fa81e9,
            version: 131584,
            flags: 0,
            hash_offset: 143,
            ident_offset: 52,
            special_slots: 3,
            code_slots: 4,
            code_limit: 14784,
            hash_size: 20,
            hash_type: kSecCodeSignatureHashSHA1,
            page_size: 4096,
            scatter_offset: Some(
                0
            ),
            ident: "org.mozilla.firefox",
            special_hashes: {
                Requirements: Hash { a2fff73cccc90e1ba55e2697a6bccce52a3a949d },
                CodeDirectory: Hash { 9c4613fabb12a16ac2ad4af398b084daa2839869 },
                Info: Hash { 2fec4b460e9eae9b79a08f8d4ac1208182edd3e9 }
            },
            code_hashes: [
                Hash { 92a000cd4496a7a660d31e11e4daa5a7cebbeaf8 },
                Hash { 2a442dcdfc7eba0f63f1924390954a3a896c8bf4 },
                Hash { 8f3fc78802e1023f4449ff0339413d6b286b1cba },
                Hash { c4e57946b957bfd1434ed38a34df46a96d563748 }
            ]
        }
    ),
    2: Requirements(
        Requirements (hash=SHA-1:2fec4b460e9eae9b79a08f8d4ac1208182edd3e9) {
            3: Requirement {
                kind: 1,
                expr: Or(
                    And(
                        AppleGenericAnchor,
                        CertGeneric
                    ),
                    False
                )
            }
        }
    ),
    65536: BlobWrapper(
        ...
    )
}
```
Running it on Nightly 64.0a1 shows very similar output so I will not paste it here. The tool also implements an `extract` command to extract just the PKCS#7 signature to a file, run it like `cargo run extract /path/to/binary /tmp/signature` and it'll place the signature in /tmp/signature.

Implementation-wise I don't have a strong preference between your first two suggestions (I don't have any real Go experience so I'd defer to someone who does). I would recommend against reimplementing this code in Go unless you have a very strong need to--it's pretty hairy and I spent *a lot* of time reading Apple's source to get as far as I did.

In terms of what we'd need to do with my existing code to do actual code signing, we'd need to:
* Add support for calculating the special slot hashes. I don't think this is very complicated, I have code in there for the requirements already.
* Add support for generating a code directory and signature blob for an unsigned binary. Right now the code just parses an existing signature blob, but once it can calculate all the necessary hashes it should be able to generate one from scratch. This is mostly straightforward except for serializing the data back to disk, but it's not a huge amount of work.
* Add support for a few other things like app bundles, detached signatures, etc. We definitely need app bundle support to sign Firefox, and it's likely we need detached signature support for something. I don't think these will be very hard compared to dealing with the signature blob itself.

Once we have all that the steps to sign an app would look like:

1. Rust code takes the app bundle, generates a code directory.
2. Rust code provides the hash of that code directory
3. Go code generates a PKCS#7 signature for the code directory hash
4. Rust code combines the code directory and signature into a signature blob, embeds it into the binary

For the actual integration in steps 2-4 I'm ambivalent about the specifics. We could just make the Rust code into a standalone tool with a "generate code directory hash" command and an "embed PKCS#7 signature" command, and have the Go code shell out to the tool for step 2, generate the signature, and shell out to it again for step 4. We could alternately have the Rust code expose a C API and use Go FFI to call the necessary APIs directly.

@jvehent and I are both going to be at a work week next week, so we can discuss specifics in person if that'd be helpful.

**Comment by luser** [comment]
Greg and I had a quick chat just now, and the integration should actually be even simpler than what I described above. Since autograph is a network service what we'll wind up doing is writing a pure-Rust tool that can calculate the code directory hash, that hash will get sent to autograph, which will return a PKCS#7 signature, and then the Rust tool will insert that signature into the binary. Most of the integration bits here will be in RelEng's signing scripts which will have to invoke the Rust tool and call out to autograph (which they're already doing for other signing formats). I should be able to find time to get my Rust code into usable shape in Q1 2019, I'll make sure to chat with the right folks in RelEng before I get too far so that we are all on the same page.

**Comment by jvehent** [comment]
This is on hold until we decide how to handle notarizing: https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

**Comment by jvehent** [comment]
WONTFIX, we'll use mac minis for notarization for now.
