### ISSUE TITLE
Add gpg signer

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#151]
Use cases:

* sign java libs (e.g. GeckoView type things with http://maven.apache.org/plugins/maven-gpg-plugin/sign-mojo.html)
* sign Fx linux artifacts e.g. [SecureApt](https://wiki.debian.org/SecureApt) for .deb and sigs for tarballs

This should implement `/sign/hash` or `/sign/data`.

Initial WIP PR: https://github.com/mozilla-services/autograph/pull/140

ulfr per IRC:

> this is what I was referring to: the pgp signing function takes a hash that's already initialized but not finished https://github.com/golang/crypto/blob/master/openpgp/packet/signature.go#L511
> then it appends a suffix to it and returns the digest https://github.com/golang/crypto/blob/master/openpgp/packet/signature.go#L495
> I think we could implement a custom hash function that takes the provided hash and lets the pgp package adds the suffix

Alternatively we could talk to the gpg2 agent and possibly keep the key on the HSM: https://security.stackexchange.com/questions/153191/use-a-pre-calculated-hash-for-signing-a-file-with-gnupg

**Comment by g-k** [comment]
example java lib from jlorenzo we'd want to sign: https://maven.mozilla.org/maven2/org/mozilla/geckoview/geckoview-nightly-x86/64.0.20181005102515/geckoview-nightly-x86-64.0.20181005102515.aar

**Comment by g-k** [comment]
Closing since we landed https://github.com/mozilla-services/autograph/pull/140, but further testing is required.

**Comment by g-k** [comment]
Closing since we landed https://github.com/mozilla-services/autograph/pull/140, but further testing is required.

**Comment by g-k** [comment]
From meeting, @escapewindow estimates ~10GB per release and ~4GB of partner repacks and @jvehent suggests starting with the Java library signing.

**Comment by escapewindow** [comment]
Might be ~10GB of linux tarballs + ~5-25GB (large range; we can dig and get a real number. tricky thing is each partner defines its own subset of locales, platforms, + sub-configs, so we can't get a number per partner and extrapolate) of partner repacks.
