### ISSUE TITLE
Support signing APKs with DSA private keys?

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#155]
Certain older APK keys that will not be named are not RSA nor ECDSA.

To support signing APKs with them we'll probably have to:

* change signer key loading to recognize and https://github.com/mozilla-services/autograph/blob/master/signer/signer.go#L101 to return dsa keys 
* likely change the apk signer
* possibly change [the Mozilla golang pkcs7 lib](https://godoc.org/go.mozilla.org/pkcs7) too

**Comment by jvehent** [comment]
Interestingly, @jcj seemed more concerned about the dependency on sha1 than on dsa for signing APK. Reasoning makes sense: an attacker can add just as much data as they want to reach a sha1 collision. 

Are you taking this one, or do you want to me take a crack at it?

**Comment by g-k** [comment]
@jvehent all yours, haven't touched this one.

Also, interesting that SHA1 is more concerning.
