### ISSUE TITLE
automate end to end XPI testing

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#160]
For use from CI and monitor to reduce QA and handle more variants, modify the web-ext CLI tool.
refs: https://github.com/mozilla/addons-server/issues/9308

It should:

* sign an XPI with various options using autograph (possibly with addon-server too)
* create a new temporary profile
* load the addon and check (logs or return codes) for errors (e.g. this extension is corrupt)
* optionally, set `xpinstall.signatures.dev-root=true`, `security.signed_app_signatures.policy` other Fx about:config params
* optionally, launch different browser editions

Currently web-ext, loads in temporary mode and doesn't check addons.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/web-ext_command_reference#web-ext_run
https://blog.mozilla.org/addons/2015/12/23/loading-temporary-add-ons/

cc @chartjes

**Comment by jvehent** [comment]
I believe @mozmark 's autograph canary is the implementation of this end to end testing.

**Comment by g-k** [comment]
> I believe @mozmark 's autograph canary is the implementation of this end to end testing.

Yep, closing this issue in favor of tracking that deployment in https://bugzilla.mozilla.org/show_bug.cgi?id=1612145
