### ISSUE TITLE
Send signer and auth ids as statsd metric tags for signing requests

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#161]
This will help with knowing whether we can safely update configs e.g. to migrate and remove signers and authorizations.

**Comment by g-k** [comment]
I think these can just be tags to statsd counters.

**Comment by g-k** [comment]
We want to more easily know who (auth ID), signed what (input hash), how (signer ID and request options) and when (start and end timestamps, and roll up for a given period of time).

This will make it easier to track usage (to plan deploys and infra provisioning) and deprecate or remove API-level options.

**Comment by jvehent** [comment]
Since we log the `user_id` and `signer_id` in the application logs that go to stackdriver, I suggest we close this issue.

**Comment by g-k** [comment]
yeah, we do for successful signing requests.

I was thinking we should make sure we have it for failed and errored
requests possibly use a golang context for signing requests.
