### ISSUE TITLE
Add signer for a dev instance of remote settings

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/autograph#175]
Could we have a signer defined in `autograph.yml` so that Firefox can verify signatures from a local Remote Settings server? 

The signer name that Firefox expects is `remote-settings.content-signature.mozilla.org` and we fetch the x5u cert chain 
https://searchfox.org/mozilla-central/rev/d850d799a0009f851b5535580e0a8b4bb2c591d7/modules/libpref/init/all.js#2702
https://searchfox.org/mozilla-central/rev/d850d799a0009f851b5535580e0a8b4bb2c591d7/services/settings/remote-settings.js#579-581

There seems to be one for normandy already :) 

Thanks!

**Comment by g-k** [comment]
Sure! @jvehent how did you generate the normandy dev key?

**Comment by jvehent** [comment]
It was locally generated and isn't in any way related to the firefox pki. I didn't keep the root so we'd need to make a new root & chain for kinto.

**Comment by g-k** [comment]
@jvehent is generating the dev root test PKI documented somewhere?

**Comment by jvehent** [comment]
I guess that would be in https://github.com/mozilla-services/autograph/blob/5fbc20b59464571eeee2db798438b760fb0a1a7d/tools/softhsm/genpki.go when this gets merged.

**Comment by leplatrem** [comment]
I really wish we could run a local instance of remote settings from which Firefox can validate signatures.

Could you please look at this?

Thanks!

**Comment by jvehent** [comment]
Fixed in #253
