### ISSUE TITLE
travis ci failure for TestId

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#200]
Saw this test failure on Travis CI:

```
=== RUN   TestId
--- FAIL: TestId (0.00s)
    id_test.go:17: ids have wrong length, should be 25/26, got: zc4thmdmkm6id2q08k9xlzk:23, 18p2f9trm8jbp29s0dn1doaadi:26, bzlsxuzz1pzm17ukjdhq9rzkl:25
```

**Comment by g-k** [comment]
rerunning the test fixed the issue: https://travis-ci.org/mozilla-services/autograph/builds/470248084?utm_source=github_status&utm_medium=notification

**Comment by jvehent** [comment]
randomness is hard

**Comment by g-k** [comment]
Closing for now. Will reopen if it fails again / gets more annoying.
