### ISSUE TITLE
Add x5u for dev chain of trust, hosted on github

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/autograph#21]

**Comment by jvehent** [comment]
This is blocked until we have more information about the format of signing certificates (EKU, ...). cc @franziskuskiefer and @mgoodwin

**Comment by franziskuskiefer** [comment]
we will be using unique EKUs for each "context" (will be defined shortly). So the signing certificate will be a normal EE certificate without any KU bits and a EKU according to its "context" (things it's allowed to sign). Is there any other information you need despite the EKU values?

**Comment by jvehent** [comment]
That sounds good to me. I'll be waiting for the spec (EKU values) to implement it. Aside from that, maybe an openssl config example, but I can also figure it out myself.
