### ISSUE TITLE
Add additional awesomeness to __heartbeat__ endpoint.

### ISSUE THREAD

**Issue by Micheletto** [mozilla-services/autograph#25]
The present __heartbeat__ endpoint is functional but could use a bit more awesomeness.  Particularly, as more features are implemented, it would be good if they were rolled into the health check here.

Here's a really good example from the Hello project:
https://github.com/mozilla-services/loop-server/blob/a4068bc919ed02ec870caaa49492f7401d55c2be/loop/routes/home.js#L35-L97

**Comment by jvehent** [comment]
Done.
