### ISSUE TITLE
Add gomodule support for go-cose and other moz-owned libraries autograph uses

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#255]

**Comment by g-k** [comment]
WIP https://github.com/mozilla-services/go-cose/pull/53

**Comment by jvehent** [comment]
@g-k if you could merge & close https://github.com/mozilla-services/hawk-go/pull/10, we'd be done here.

**Comment by g-k** [comment]
yaml.v2 404s preventing us from running `go mod tidy` with an empty cache (checked in autograph-edge need to repeat here)

refs: https://bugzilla.mozilla.org/show_bug.cgi?id=1587843
