### ISSUE TITLE
multiple signature files in xpi

### ISSUE THREAD

**Issue by cunyx** [mozilla-services/autograph#267]
More a question than an issue, perhaps a feature request:

Being relatively new in most related areas, locally I tried to address some aspects of
supporting multiple signature files in a XPI archive
created with autograph (v. 3.0.2).

Might this be of interest for this repository?

If yes, I need to do some cleanup and I'll have to inspect how to handle
and work with this github thing.

Otherwise I'll have to keep patching new releases downstream.

**Comment by g-k** [comment]
Hi @cunyx, what's your use case?

Generally speaking autograph supports Mozilla's signing needs first, but depending on the size and applicability of your patch we might be able to accept it.

With regard to supporting multiple signature files I think we'd need to address how to:

* reserve signature filenames to prevent people from to injecting unauthorized signatures
* specify which signature filenames and formats (i.e. PKCS7 or COSE at `META-INF/mozilla.rsa` and `META-INF/cose.sig` respectively) an XPI signer uses in its config

so it might be tricky.

**Comment by cunyx** [comment]
> Hi @cunyx, what's your use case?

Thank you for the reply @g-k !

1.
As AddOn developer I'd like to xpi-sign my extension with the help of an own
instance of autograph to prove to the users, that the code has not changed
in the time between release and signing by Mozilla via addons.mozilla.org .

Currently the one and only signature guarantees integrity since
adding the Mozilla signature but this does not necessarily cover non developer
code changes after the release or edits by the (perhaps compromised)
signing authority.

Tolerating previous signatures needs cooperation from the autograph operated
by Mozilla, to not throw away existing signatures in the submitted xpi.


2.
a.
When distributing a browser, while not being Mozilla, and running an own
autograph instance to sign AddOns with an (additional) own root signing key,
shipped with a patched browser, the browser should trust and run AddOns,
that are signed (only) by Mozilla, (only) with my key or with both.

This would need the ability to have multiple signatures in the xpi and it
shouldn't matter if the xpi is first submitted to AMO or signed with the
browsers' key(s).

If this feature is only available in my autograph version but not in the one
operated by Mozilla, the xpi will loose "my" signatures when Mozilla adds her.
Therefore "my" signatures has always to be the last - that isn't ideal.

b.
As browser distributor, AddOn signer and autograph user, who is not Mozilla,
I'd like to not have to name my signature files "mozilla.sf" and "mozilla.rsa",
because I do not want to pretend to be Mozilla and perhaps violate trademarks etc.


[...]
> With regard to supporting multiple signature files I think we'd need to address how to:
> 
>     * reserve signature filenames to prevent people from to injecting unauthorized signatures

In my naive view it might be useful, if Firefox would only check "mozilla.sf"
and "mozilla.rsa" and ignore other signatures but I do tend to remember,
that it looks for "*.sf" and "*.rsa".

>     * specify which signature filenames and formats (i.e. PKCS7 or COSE at `META-INF/mozilla.rsa` and `META-INF/cose.sig` respectively) an XPI signer uses in its config
> 
> 
> so it might be tricky.

If you do say so as the expert it is very likely, that I do not foresee the
possibly dangerous consequences and other implications of adding such a
feature or parts of it.
I do not claim to have much insight and do not know, what harm some special
crafted signature files can do.


I might take this as an opportunity to learn some things about the github
workflow and try to give you a chance to look into my probably not very clever
proposal.

This will take some time and failures are likely.

When ready, perhaps you (or someone else) can give some hints where the tricky
parts start and where i enter deep and dangerous waters.

If you discover something useful, you might want to cherry pick some snippets or
point me to possible improvements.

**Comment by g-k** [comment]
Hey @cunyx! Thanks for the additional info. I'm still thinking about all the implications here, but re: 2b we could make the signature prefix configurable in [the XPI signer configuration](https://github.com/mozilla-services/autograph/tree/master/signer/xpi#configuration)

The new config would look like:

```yaml
- id: webextensions-rsa
  type: xpi
  mode: add-on
  signaturePrefix: mozilla  # or whatever you're calling it
...
```

and you'd need to update [the XPI signer initializer](https://github.com/mozilla-services/autograph/blob/db863e066a4001d438e7e2af53396d04d11435e5/signer/xpi/xpi.go#L94) to read that config value and set the signature paths (which would need to be converted from [hardcoded values](https://github.com/mozilla-services/autograph/blob/db863e066a4001d438e7e2af53396d04d11435e5/signer/xpi/xpi.go#L46-L47) to fields on the signer instance). I believe the python addons-server signing function supported this feature for testing.

**Comment by cunyx** [comment]
[...]
> I'm still thinking about all the implications here,
> but re: 2b we could make the signature prefix configurable

[...]

Thanks for the pointers @g-k !

This was my starting point, using "owner" as option name, as well.

When having it somehow usable implemented and after signing an already signed
xpi (by another "owner"), I realized that existing signatures are not copied
into the repacked xpi.

From there my code changes evolved further to keep "old" signatures and made it
necessary to reflect the edits to other parts of autograph that had to be made
aware of the currently signing "owner". For example autograph-client, tests,
readme file, some functions, ...

It is very likely that I missed areas that should be adjusted. For example I
haven't figured how to add an encrypted default value for the "owner" option
to the encrypted configuration file.

I'm planing to push my changes to
https://github.com/cunyx/autograph/tree/multiple-xpi-signatures
when my tools are setup properly.

As soon as there is something to look at, I'll post a notice here.

If you will (perhaps for the moment) want to only upstream the commits that are
needed to address use case 2.b., you might want to pick a subset of my changes
or I'll create an additional branch, that only includes what is needed to
configure and use the "owner" option to prefix the signature files
(not sure what the preferred development process might be).

**Comment by cunyx** [comment]
After preparing some parts of the pkcs7 side of the topic,
I realized a few things:

a.
Cose signatures will lead to changes in manifest.mf and break existing pkcs7
signatures.

b.
Cose signatures might be the future and support for pkcs7 signatures for
browser extensions might end. Is this possible or already decided?

c.
Supporting different file name prefixes for cose signatures in a world without
pkcs7 signature files would need at least cose.sig and perhaps cose.manifest
files to have a name configured by each signer.

d.
Applications verifying the signatures should ignore signatures and manifests
that rely on not trusted signing keys.
They have to be capable to not fail if more than one of each file is in
the "META-INF" directory.
They must be able to choose the right .sf, .rsa, .sig, etc. file(s)
while doing signature verifications.

e.
Firefox might currently not be able to accept an extension with multiple
signature files. see:
https://searchfox.org/mozilla-central/rev/75294521381b331f821aad3d6b60636844080ee2/security/apps/AppSignatureVerification.cpp#162

f.
Firefox uses hard coded file name values for cose.sig and the manifests. see:
https://searchfox.org/mozilla-central/rev/75294521381b331f821aad3d6b60636844080ee2/security/apps/AppSignatureVerification.cpp#328


This brought some conclusions:

A.
Each pkcs7 xpi signer needs a separate manifest like "mozilla.mf" which has to
be preserved in addition to the signature files *.sf and *.rsa . Otherwise
following cose signatures will render the previous pkcs7 signatures invalid.

B.
If we will have only cose signatures in the future, working on supporting
multiple pkcs7 signatures seems a bit wasted.

C.
I'm not sure if there is some spec dictating to name cose signatures only
"cose.sig" and "cose.manifest" and if they are allowed to not include signature
files added by signers who add their signatures later.

D.
If autograph aims to fulfill Firefox' needs, it might not want to add a feature
that is currently unsupported by Firefox and will especially not enable it by
default and on AMO until all supported Firefox versions are patched accordingly.

E.
The browser sources need to be adjusted first to not fail in case of multiple
signatures before autograph will by default not throw existing signatures away.


As E. is nothing I can influence in regard to Firefox, my proposal (if
implemented in autograph), won't be enabled by default on AMO.

So, I currently don't see how the use cases 1 and 2.a can be solved by patching
(only) autograph upstream.
This might change if Firefox decides to tolerate the existence of signature
files from other entities.


Please correct me, if the assumptions or conclusions are wrong.


What might be needed to support use case 2.b is pushed to
https://github.com/cunyx/autograph/tree/xpi-owner

Perhaps someone wants to have a look. Feedback welcome!

**Comment by g-k** [comment]
Hey @cunyx,

> a. Cose signatures will lead to changes in manifest.mf and break existing pkcs7 signatures.

Yes, the COSE signature and manifest files are included in the PKCS7 manifest for older clients.

> b. Cose signatures might be the future and support for pkcs7 signatures for browser extensions might end. Is this possible or already decided?

Yes, Mozilla is migrating from PKCS7 signatures to COSE for webextensions. This is a multi-year process to stop using SHA1 hashes (which can be broken with enough compute power).

There's a pref in the browser (the name escapes me at the moment but I think it's mentioned for QA in the PR adding COSE support #57) to control whether PKCS7 or COSE signatures are used and validated.

> c. Supporting different file name prefixes for cose signatures in a world without pkcs7 signature files would need at least cose.sig and perhaps cose.manifest files to have a name configured by each signer.

Since you we talking about the `mozilla.*` files I was figuring you wanted to stay on PKCS7 and ignore COSE (they are not included by default only when a COSE signature is requested), but you could add `$owner.cose` files or another signer config field for COSE filenames.


re: d. , e., and f. this is outside my expertise, but you will need to tweak things and recompile mozilla-central to maintain a fork

> A. Each pkcs7 xpi signer needs a separate manifest like "mozilla.mf" which has to be preserved in addition to the signature files *.sf and *.rsa . Otherwise following cose signatures will render the previous pkcs7 signatures invalid.

Yes, you'll need a manifest per owner or your browser webextension loading logic will need to know which manifests to use with each owner.

> B. If we will have only cose signatures in the future, working on supporting multiple pkcs7 signatures seems a bit wasted.

Yes if you don't need backwards compatibility with PKCS7-signed extensions.

> C. I'm not sure if there is some spec dictating to name cose signatures only "cose.sig" and "cose.manifest" and if they are allowed to not include signature files added by signers who add their signatures later.

There are specs for COSE and CBOR and webextensions, but I'm not aware of any specs for webextension signing and I believe that's vendor specific.

> D. If autograph aims to fulfill Firefox' needs, it might not want to add a feature that is currently unsupported by Firefox and will especially not enable it by default and on AMO until all supported Firefox versions are patched accordingly.

I'm not totally sure which features you're talking about, but autograph is solely focused on signing for Firefox. We'll consider landing changes that we can use (like the owner config value) if they can help with testing or don't incur much overhead. And yes Mozilla is unlikely to enable things in autograph or AMO that Firefox won't need or use.

> E. The browser sources need to be adjusted first to not fail in case of multiple signatures before autograph will by default not throw existing signatures away.

Right you would need to patch, compile, and distribute a browser fork and probably run autograph and AMO servers to sign and distribute webextensions for it.

> As E. is nothing I can influence in regard to Firefox, my proposal (if implemented in autograph), won't be enabled by default on AMO.

Right you'd need to convince people in firefox-dev or another mailing list. Also, AMO is similarly Firefox-focused.

> So, I currently don't see how the use cases 1 and 2.a can be solved by patching (only) autograph upstream. This might change if Firefox decides to tolerate the existence of signature files from other entities.

Right, to run a Gecko fork with a webextension store you would probably need to run autograph and AMO forks too.

re: use case 1 you can resign your addon on AMO as a new version or new addon and re: use case 2a adding your signatures after AMO's would work.

Generally speaking the AMO team deals with quite a bit of abuse day-today, so we try to be strict about signing in autograph and addon review in AMO to protect our users from malware. To that end it's unlikely we'll want to accept signatures from other entities, but maybe there's a compelling use case for doing that.

I hope that answers your questions. The changes in that branch look good, so if you want to make a PR I'll review it when its ready or see what I can cherry-pick out.

**Comment by cunyx** [comment]
> Hey @cunyx,

Thank you for the all the comprehensive answers @g-k !

[...]
> Since you we talking about the `mozilla.*` files I was figuring you wanted to
> stay on PKCS7 and ignore COSE (they are not included by default only when a
> COSE signature is requested),

Yes, that was my first idea, what had been implemented and was somehow working.
But after inspecting some freshly AMO signed extensions, I saw the added COSE
signatures and their reference included in manifest.mf .
This brought me to the conclusion, that COSE can't be ignored when doing
PKCS7 (only) signing for my use cases and if COSE is the future, this has to be
addressed  anyway (earlier or later), especially if PKCS7 support might be
dropped from the browser source code one day.

> but you could add `$owner.cose` files or another signer config field
> for COSE filenames.

Thinking about it, it might be best, if Mozilla would use "mozilla.sig"
instead of "cose.sig". Thereby the "owner" option can cover all prefixes.

But as this seems to be unlikely to happen,
it is perhaps necessary to hard (pseudo) code:

if owner == "mozilla" than name COSE signature "cose.sig"

This makes an additional config option unnecessary but as a consequence the
proposed function "IsValidOwner" would need some kind of blacklist for
reserved "owner" names, e. g. "cose" and perhaps more.

It might be desirable to include such a blacklist from the start in order to
have no autograph version, where "cose" was a valid value for "owner".

[...]
> Yes, you'll need a manifest per owner or your browser webextension loading
> logic will need to know which manifests to use with each owner.

Yes, both seems to be needed, when cose signatures are fiddling with the
manifest.mf after "my" owner added his signature.

[...]
>> D. If autograph aims to fulfill Firefox' needs, it might not want to add a
>> feature that is currently unsupported by Firefox and will especially not
>> enable it by default and on AMO until all supported Firefox versions
>> are patched accordingly.
> 
> I'm not totally sure which features you're talking about,

To keep, by default, existing signature files from other owners in the xpi
when adding a new signature.

> but autograph is solely focused on signing for Firefox. We'll consider
> landing changes that we can use (like the owner config value) if they can
> help with testing or don't incur much overhead. And yes Mozilla is unlikely
> to enable things in autograph or AMO that Firefox won't need or use.

Understood.
[...]

> Right you would need to patch, compile, and distribute a browser fork and
> probably run autograph and AMO servers to sign and distribute webextensions
> for it.

Yes. Much work it is. Instead of AMO there might be other options but the
browser and autograph sources have to be patched,
where changes can't be upstreamed.

[...]
> Generally speaking the AMO team deals with quite a bit of abuse day-today,
> so we try to be strict about signing in autograph and addon review in AMO
> to protect our users from malware. To that end it's unlikely we'll want to
> accept signatures from other entities,

Ignoring but including them in the newly signed xpi, would be enough ;)

> but maybe there's a compelling use case for doing that.

If this is a question. some ideas:

I.
Instead of using the certificates "OU" to differentiate extension modes/scopes,
it would be possible to use combinations of "owner" and different trusted root
certificates to handle extensions with their varying permissions or purposes.
This might give more flexibility.

II.
Migration to a new root certificate might be easier as well, because the new
root can be rolled out in parallel to the existing one and extensions can have
multiple signatures.
This reduces the risk of breakage if the old root cert gets disabled.

Now you have only "mozilla.sf" as signature from root OLD,
during migration you can add "mozilla_new.sf" with signature from root NEW
that are both valid,
after migration only "mozilla_new.sf" with signature from root NEW is trusted.

III.
The same logic applies and shields against the case of a lost or compromised
root certificate. Currently it might be considered "game over" if the only
trusted root certificate isn't available/trusted anymore.
If a second signature from another root certificate is added and shipped with
the browser, already now, it will be much easier to untrust the compromised
signing key and switch trust to the already included fallback signatures.

IV.
Key rollover can be done easier and therefore in shorter intervals what some
people say, is more secure.

V.
Mozilla might want to give Firefox special builds, test versions or friendly
forks the ability to accept webextension signatures from AMO and from other
repositories or AddOns with special purpose signatures.

VI.
Users Mozilla wants to protect, might have more confidence and feel more
protected, if code they use (extensions) is signed by entities they trust even
more than Mozilla (for example: them self, developers they know personally, the
vendor of their operating system, etc.).

> I hope that answers your questions.

Yes, thank you very much!

> The changes in that branch look good, so if you want to make a PR I'll review
> it when its ready or see what I can cherry-pick out.

I'll try it. Will be my first one - please don't expect everything to be right
and me handling the tools correctly in the first round.
If something is missing, I should add or do somethings in another way,
please say so.

You can pick and/or modify want you want.

**Comment by cunyx** [comment]
The opportunity to extent point III. was too good:

In case of an expiring intermediate certificate a second
chain of trust with still valid certificates would prevent
AddOns from getting untrusted/disabled until a member of the
trusted fallback chain expires as well.

**Comment by jvehent** [comment]
Thanks for the great discussion in this issue. We haven't had time to review #285 in details yet, but besides the code I think there's a product discussion that needs to happen with the Firefox add-ons team. @jvillalobos is a good contact for that.

Fundamentally, if you wanted to tell users that an extension was issued by you, there's nothing stopping you from adding a signature file in the xpi, and we'll simply keep it when we issue the pkcs7. But if your goal is to have Firefox do something with your own signature, then it's a much taller order.

**Comment by jvillalobos** [comment]
I don't expect us to support anything beyond our current signing process. Like Julien said, if there are files you can include in the package that don't interfere with signing, it's not a problem to have them there, and they will be preserved.

**Comment by cunyx** [comment]
Thanks for your comment @jvehent  !

[...]
> there's nothing stopping you from adding a signature file in the xpi, and we'll simply keep it when we issue the pkcs7.

What was stopping me a few month ago, was my understanding of the verification code of Firefox that seemed to be unable to cope with this additional (untrusted) signature files.
Do you think that this was a misunderstanding or if it is not an issue anymore?

My conclusion was, that the autograph version used by AMO won't allow multiple signature files and will continue throwing those added by another autograph instance (run by a WebExtension developer) away, until Firefox gets "fixed" first.
That's perhaps the point where "a product discussion" is needed?

> But if your goal is to have Firefox do something with your own signature, then it's a much taller order.

For my (use case) ideas it would have been enough, if Firefox is able to ignore signature files not owned by Mozilla.

On top of it, in my opinion, Firefox would gain from the ability to have and use multiple signature files or chains of trust as described in the various scenarios before.

**Comment by cunyx** [comment]
Thanks for chimming in @jvillalobos !

> I don't expect us to support anything beyond our current signing process.

I have to accept that but hoped, changes, that might be improvements, are at least considered.

As described, my proposal might have prevented/delayed armagaddon if it was considered and implemented before.
For those without a look from the insight, it seems there might have been some space where the signing process could have performed better.

> Like Julien said, if there are files you can include in the package that don't interfere with signing, it's not a problem to have them there, and they will be preserved.

Will wait for an answer to my previous post, but at least some months ago, autograph (upstream) didn't preserved these files.

To allow changing this on the autograph side, it might be wanted to first teach
security/apps/AppSignatureVerification.cpp
to either only consider "mozilla".* signature files, or to not fail verifying if more than one possible candidate file is found.

It would be great if Firefox is able to adapt here in order to allow autograph to include the developer signatures.
