### ISSUE TITLE
Rework data input

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/autograph#27]
The format of `signature requests` is too obscure:
* `input` is used for any type of data input, whether it's a hash or raw data
* `hashwith` tells autograph if `input` needs to be hashed
* `template` tells autograph if the input needs to be modified before hashing

This leads to confusion. I'd like to simplify as follows:
* `b64rawinput` is a base64 encoded string that contains raw, non hashed, input data.
* `b64hashinput` is a base64 encoded string that contains hashed data

with the following rules:

1. modifications on `b64hashinput` are forbidden, meaning if either `hashwith` or `template` are set on a signature request that contains non-empty `b64hashinput`, an error will be returned to the caller.
2. `b64hashinput` and `b64rawinput` are mutually exclusive. If both are non-empty in a signature request, an error is returned to the caller.
3. if only `b64rawinput` is set, and no `hashwith` value is set, the hash algorithm in inferred from the private key (for example: P-384 will use SHA-384).
4. On `b64rawinput`, no `template` is applied unless explicitly requested. A consequence of this: on `b64rawinput`, the `content-signature` value is not returned if no `template` is requested (`content-signature` requires `template: content-signature` in the signature request). On `b64hashinput`, `content-signature` is always returned, as we assume the caller performed the templating prior to calling autograph.

Examples:

1. caller wants a signature on a hash
```json
[ { "b64hashinput": "oidh19OQSHAD971eh==" }]
```
2. caller wants a content-signature on raw input:
```json
[ { "b64rawinput": "Y2FyaWJvdW1hdXJpY2UK", "template": "content-signature" } ]
```

@ncloudioj @almet : thoughts?

**Comment by almet** [comment]
Since you're not exposing the same validation methods for "hashed" and "raw" inputs, have you considered having two different endpoints?

- Doing a `POST` on `raw/signature/` when pushing raw data. A `template` parameter can be specified.
- Doing a `POST` on `hash/signature/` when pushing hashed data.

**Comment by jvehent** [comment]
Not a bad idea. It would simplify documentation too, as each endpoint supports fewer parameters and rules.

**Comment by ncloudioj** [comment]
+1 for splitting the endpoint.
