### ISSUE TITLE
multiple gpg2 signers fail with "cannot allocate memory"

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/autograph#333]
When running autograph with 2 or more gpg2 signers, parallel signing requests make the gpg2 binary fail with 

```
500 Internal Server Error signing failed with error: gpg2: failed to sign input exit status 2
gpg: signing failed: Cannot allocate memory                                                                                     
gpg: signing failed: Cannot allocate memory                                                                                     
: exit status 2
request-id: khGxaeJ9MU9vVZ47
exit status 1
```

I'm unsure why this happens. It could be located inside a gpg-agent shared between gpg invocation. An easy fix would be to implement a global lock so only one gpg2 signing operation can be processed at a time. It's sad, but it would work.

**Comment by g-k** [comment]
Fixed in #332 

Research from elsewhere suggests gpg2 does not support concurrent signing.
