### ISSUE TITLE
Publish chain of trust on S3

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/autograph#35]
Upon initialization, publish the chain of trust in a S3 bucket. The file will contain, in this order:
1. end entity certificate
2. intermediate signing cert
3. root cert

What should the chain of trust file be named? It should be something unique. We could take the public key hash of the EE cert, or we could use the Subject.CN + expiration date. The latter is more human readable.

@mozmark / @franziskuskiefer:  thoughts?

**Comment by franziskuskiefer** [comment]
I like Subject.CN + expiration date

**Comment by jvehent** [comment]
It only took three years, but this is now merged in master via #208 !
