### ISSUE TITLE
reduce monitor overhead

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#464]
Currently, monitoring via the `/__monitor__` endpoint scales linearly with <# of monitor requests> and <# of signers>.

This:

* consumes CPU and memory representing a potential DoS vector 
* introduces latency for real signing requests especially for signers that shell out or lock and shell out like the `gpg2` signer (TODO: measure actual CPU and memory overhead)
* adds complexity to deployments i.e. what succeeds with one config might not work with another

**Comment by g-k** [comment]
Possible solutions:

* sign a monitor request every `<duration>` and cache it in memory and return that cached data for all monitor requests to address scaling with # of monitor requests
  * split monitor signing requests per signer so they aren't all fired off at once
  * wait until memory and CPU usage is lower before resigning 

* sign one signer type per monitor request

**Comment by gterzian** [comment]
Ok I would like to take a shot. I propose the following design:

1. On start-up:
  - let `snapShot` be a snap-shot of the list of signers(assuming that doesn't change after). 
  - let `closeChan` be a channel.
  - let `monitorResultCache` be a map, and an associated rwlock. 
  - let `monitor` be a new goroutine, uniquely owning `snapShot`, and sharing `closeChan` and `monitorResultCache` with the autograph instance. 
2. Inside `monitor`:
  - let `monitorAlgorithm` be an algorithm that  that checks all signers, storing each result in `monitorResultCache`.
  - run `monitorAlgorithm`.
  -  Inside a loop:
    - select on:
       - `closeChan` -> break out of the loop
       -  a timer -> run `monitorAlgorithm`
3. Inside the monitor route handler:
  - get results from `monitorResultCache` and communicate them back to the client in the http response.
4. On shutdown of the autograph instance:
  - close `closeChan`

Note: I think the rwlock can be a simple mutex if we can exclude the possibility of step 3 running in parallel of each other.

**Comment by g-k** [comment]
Hi @gterzian (always good to meet another Greg!), that plan sounds great thanks for the suggestion!

> let snapShot be a snap-shot of the list of signers(assuming that doesn't change after).

This is true: signers are loaded once when the server starts. We've discussed moving signer configs to the database, but have no plans to implement that.

> Note: I think the rwlock can be a simple mutex if we can exclude the possibility of multiple concurrent step 3.

There are a few monitor lambdas running, but we don't need crazy throughput. Reading from the in memory cache should be much faster than signing everything and we could serialize requests for one handler.

Also, https://github.com/mozilla-services/autograph/tree/master/tools/autograph-monitor is the only client using the `/__monitor__` route so we can configure the timeouts it uses.

We do have high memory usage in the monitor too which might be worth considering (since it does a naive [`ioutil.ReadAll`](https://github.com/mozilla-services/autograph/blob/master/tools/autograph-monitor/monitor.go#L136)). But we don't need to address it in this issue.

**Comment by gterzian** [comment]
Awesome, I'll open a PR and we can take it from there. 

> We do have high memory usage in the monitor too which might be worth considering (since it does a naive ioutil.ReadAll). But we don't need to address it in this issue.

Ok, I would be interested in doing other slightly unrelated stuff, either in a separate commit, or follow-up PRs, as my goal is really to get more familiar with Go in general.

**Comment by g-k** [comment]
> Ok, I would be interested in doing other slightly unrelated stuff, either
in a separate commit, or follow-up PRs, as my goal is really to get more
familiar with Go in general.

That'd be great! Don't hesitate to reach out if you have questions.

**Comment by gterzian** [comment]
@g-k By the way, as a potential second iteration on this, could the normal signing request not also play a role in the monitoring, in the sense that they could pass both errors and successes to the monitor in some way, to further reduce the need for the monitor to actually sign stuff as part of the monitoring. 

For example, each successful signing request could reset some timeout for that signer, so that the monitor would only try signers that haven't been successfully used since a timeout.

So the monitor logic could become something like:

at each monitor interval:
  - Run  check for all signers that have either:
    - Not been used for a real request for a while.
    - Have errored in a real request.
