### ISSUE TITLE
FWIW, cloudhsm support lastest is 3.x, we have 2.x installed

### ISSUE THREAD

**Issue by hwine** [mozilla-services/autograph#480]
I've no idea if there's a reason to upgrade, but I did run into this yesterday (2020-0-06). It impacted our instructions on how to use `openssl` from the CLI.

The CLI workaround is [now documented](https://docs.google.com/document/d/1tVYApGVvSSyMnBrWBryev6VA_1kHm4l1XRHm9rGSZ24/edit#heading=h.nwgjptx5ti23) so there's no rush on that account.

AFAICT, this only affects a subset of CLI work (that requiring openssl to communicate with HSM). The prior need was about 7 months ago, so the upgrade occurred somewhere in that window.  (`CloudHSM-client*` are the packages which provide the library for communicating with the HSM. Production only needs `cloudhsm-client-latest`, but some manual procedures need to add `cloudhsm-client-dyn-latest`. The "-latest" part is what causes the glitch.)

**Comment by g-k** [comment]
Closing as wontfix since we came up with a workaround for the CLI tools and upgrading will require upgrading the pkcs11 and other golang packages.

For future ref was running into a CKR bad arguments error with the rand reader.
