### ISSUE TITLE
Add XPI COSE signer

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/autograph#57]
cc @mozkeeler, @franziskuskiefer and @jcjones 

Autograph needs a signer to issue COSE signatures for add-ons.

As there isn't a COSE library for golang yet, we'll need to write one, but we can reuse existing [cbor](https://godoc.org/github.com/ugorji/go/codec#CborHandle) encoders to help.

**Comment by franziskuskiefer** [comment]
@jvehent Any update on this?

**Comment by g-k** [comment]
Fixed in #76.
