### ISSUE TITLE
temp file name

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/autograph#60]
this should be avoided here  https://github.com/mozilla-services/autograph/blob/master/tools/sign-addon/sign.py#L18-L20 because you hve no guarantee no one will do something with the file before you start to actually create it.

use the secure version in the stdlib that will hand you an FD to make sure no one else is tampering with the same file

**Comment by jvehent** [comment]
I see what you mean, though I'm not sure how to fix it since `jar.make_signed` writes directly to a `outfile` path, and not to a file descriptor. Any suggestion? Should `signing_client` support writing to a FD maybe?

**Comment by tarekziade** [comment]
You should be able to pass an io.StringIO instance to make_signed() so the Zip is written in memory, then write its content directly to the fd. Don't forget to seek(0) just before writing on disk

**Comment by jvehent** [comment]
the python client is going away short term so I'll close this as wontfix.
