### ISSUE TITLE
Support verification of JAR files

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/autograph#67]

**Comment by g-k** [comment]
We have sig verification https://github.com/mozilla-services/autograph/blob/01e9306f36cbaa525598518d6567bb14de5af233/signer/apk/apk.go#L201-L206 but the comment for that function mentions manifest verification.

I believe we also run `apksigner verify` in CI though I can't find it in this repo.

**Comment by g-k** [comment]
Closing since it's unclear what the original issue is for. Presumably something like having autograph verify signed apks as a new endpoint or having the autograph client verify signed apks.

Regardless APK verification is handled in the docs.
