### ISSUE TITLE
statsd metrics in production

### ISSUE THREAD

**Issue by jbuck** [mozilla-services/autograph#675]
It looks like there are some dashboards configured with statsd metrics but aren't receiving any - could we get these re-enabled? I'm assuming it's a configuration change in the app, or maybe we need to update credentials

**Comment by g-k** [comment]
I don't think there are any creds, so we should just need to update the publish endpoint https://github.com/mozilla-services/autograph/blob/main/docs/configuration.rst#statsd

**Comment by g-k** [comment]
Moved to the private bug https://bugzilla.mozilla.org/show_bug.cgi?id=1709103
