### ISSUE TITLE
bugzilla-signer lambda function

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/autograph#70]
The bugzilla signer lambda function is an autograph client that watches a given bugzilla component for attachments to sign. The idea is to rely on bugzilla as a tracking tool while automating the signing operations of addons and mobile applications. The workflow would work as follows:

1. developer creates bug in product X component Y to request signing of application A
2. bugzilla-signer wakes up and poll the rest api for new bugs (created in last X minutes)
3. bugzilla-signer finds the new bug and grabs the attachment. Optionally, we can filter to only take bugs that have receive relman+, or something similar.
4. bugzilla-signer parses the attachment to decide how to handle it. Android apps and add-ons have in ID in their manifest that can be mapped against a configuration file to decide how to sign. Otherwise, we could also use the product/component location for that. bugzilla-signer then calls autograph with the right set of credentials to sign the attachment.
5. bugzilla-signer gets the signed attachment back and push it to bugzilla by creating a new attachment in the bug.

**Comment by g-k** [comment]
I wonder if we could piggyback on the GH driven addons signing workflow RelEng developed for this.

**Comment by jvehent** [comment]
WONTFIX in favor of addon-pipeline
