### ISSUE TITLE
debsign support

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#744]
Support signing debian packages as discussed in email thread with subject "VPN Linux signing approach".

Signer Behavior:

1. accept the dsc, buildinfo, and changes files
2. acquire the global gpg2 lock
2. Like the apk2 and gpg2 signers, shell out to [debsign](https://manpages.debian.org/stretch/devscripts/debsign.1.en.html) to run `debsign -k <my key name> --re-sign *.dsc *.buildinfo *.changes`
3. release the gpg2 lock
4. return the signed .dsc, .buildinfo, or .changes files

Assumptions:

* there aren't significant differences between the ubuntu and debian buster versions of debsign
* the `*.dsc *.buildinfo *.changes` files aren't huge (the manpage suggests they should at least be smaller than the full package)

Current estimate is ~1 week of uninterrupted time.

Alternatively, we could try to decompose `dpkg-buildpackage` to get the sign hook input or try to extract hashes, but as Ben pointed out that'd require more custom tooling and incur a higher maintenance overhead to keep up with upstream changes.

**Comment by g-k** [comment]
@escapewindow do we need to sign `.commands` files? They seem potentially problematic.

**Comment by escapewindow** [comment]
@hwine did we end up adding a signer for this, and sending your team the gpg key? We'll need that for https://mozilla-hub.atlassian.net/browse/RELENG-790 .

**Comment by hwine** [comment]
All changes appear to have been deployed with train 28 on 2021-12-01

Id's hooked to the deb signer in STAGING
- dummy_gpg2_pgpsubkey_debsign <== signer
  - debsign_test <== id to access signer

Id's hooked to the deb signer in PRODUCTION
- release_at_mozilla_debsign_dep <== signer
  - bug https://bugzilla.mozilla.org/show_bug.cgi?id=1569753
  - releng_firefox_release_at_mozilla_debsign_dep_2021  <== id to access signer
 - release_at_mozilla_debsign_rel_2021 <== signer
   - bug https://bugzilla.mozilla.org/show_bug.cgi?id=1703397
   - releng_firefox_relase_at_mozilla_debsign_rel_2021 <== id to access signer

If you don't have the hawk tokens for those ids, just holler.
