### ISSUE TITLE
Comment about use of SigningTime in xpi signer is incorrect

### ISSUE THREAD

**Issue by Rob--W** [mozilla-services/autograph#755]
The blocklist implementation currently uses `notBefore` instead of `signingTime` (see linked Firefox code in #739), but xpi.go has a comment that incorrectly claims that Firefox uses `signingTime`. This was based on my incorrect statement, which has been clarified at https://bugzilla.mozilla.org/show_bug.cgi?id=1549018#c24, along with a suggestion to switch from notBefore to signingTime anyway. Depending on your reply to that comment, we may switch to `signingTime` in Firefox, but if that doesn't happen the comment below would need to be updated.

https://github.com/mozilla-services/autograph/blob/019e7668100b690a736a148b8761cc05128e6ef6/signer/xpi/xpi.go#L381-L386

**Comment by g-k** [comment]
Ah, nice catch! I opened a PR and I'll reply in the bug.
