### ISSUE TITLE
Allow `~` characters in filenames for debsign

### ISSUE THREAD

**Issue by ahal** [mozilla-services/autograph#849]
In the debian packaging world, `~` is a special character that can be used in version strings to denote a pre-release or test package which should be prioritized below all other versions (or something like that). The important bit is that it has meaning.

Unfortunately, autograph validates all file names we sign against a regex and disallows `~`. It would make sense to support files with `~` in the name for debsign where this has meaning.

It looks like this check happens here:
https://github.com/mozilla-services/autograph/blob/0edcdc80246921740e864a56d17bf2939beb3be0/signer/signer.go#L222

The good news is that it should be simple to add `~` to the regex. The bad news is that isn't debsign specific. However, the previous check is already validating that the filename can't start with `~`. So from a security standpoint, I think this would cover malicious attempts to access the home dir? In that case maybe allowing it for all signers isn't a big deal?

**Comment by ahal** [comment]
@hwine any thoughts? Can we just add `~` to the regex here?

**Comment by hwine** [comment]
N.B. prioritization & scheduling will be handled in bug-1823721

**Comment by oskirby** [comment]
For some context, the Debian policy guide has a formal description of the package version strings [here](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version), and IIRC the `upstream_version` and `debian_version` components of that version are able to appear in the filenames of artifacts to be signed.

The TLDR is that a you can wind up with package filenames containing `[0-9A-Za-z.+-~]` (alphanumerics, full stop, plus, hyphen, and tilde).

**Comment by hwine** [comment]
PRs accepted 🙂 (with tests, of course)

Please make sure it applies cleanly to tag 4.1.6 (not main), and integration tests pass. (Note, you'll need `docker-compose` locally for `make integration-tests` to pass. We're not ready to update the tool chain to modern docker due to CircleCI issues.)
